language: python
python:
    - "3.7"
    - "3.8"

jobs:
    include:
        - script:
            python test.py
        - script:
            python test_another.py
        - script:
            - echo "Hello world"
            - echo "Try to run test_another again " && python test_another.py
