language: python
python:
    - "3.7"
    - "3.8"

env:
    - TEST=one

    jobs:
    include:
        - script: echo "First"
        - stage: Stage one
          script: echo "Second"
        - script: echo "Third"
        - stage: Stage two
          name: Fourth job
          script: echo "Fourth"
        - name: Fifth job
          script: echo "Fifth"

script: python test.py && test_another.py
