language: python
python:
    - "3.7"
    # - "3.8"

install: skip

jobs:
    include:
        - name: First
          script:
            python test.py
        - name: Second
          script:
            python test_another.py
        - name: Third
          script:
            - echo "Hello world"
            - echo "Try to run test_another again " && python test_another.py
